def gui(guess_num, word):
        if guess_num == 9:
            print("\nIncorrect guesses left: 8\n")
            print("        -------")
            print("      |/      |")
            print("      |")
            print("      |")
            print("      |")
            print("      |")
            print("      |")
            print("      |")
            print("______|_____")
        elif guess_num == 8:
            print("\nIncorrect guesses left: 8\n")
            print("        -------")
            print("      |/      |")
            print("      |")
            print("      |")
            print("      |")
            print("      |")
            print("      |")
            print("      |")
            print("______|_____")
        elif guess_num == 7:
            print("\nIncorrect guesses left: 7\n")
            print("        -------")
            print("      |/      |")
            print("      |      (_)")
            print("      |")
            print("      |")
            print("      |")
            print("      |")
            print("      |")
            print("______|_____")
        elif guess_num == 6:
            print("\nIncorrect guesses left: 6\n")
            print("        -------")
            print("      |/      |")
            print("      |      (_)")
            print("      |       |")
            print("      |       |")
            print("      |")
            print("      |")
            print("      |")
            print("______|_____")
        elif guess_num == 5:
            print("\nIncorrect guesses left: 5\n")
            print("         -------")
            print("       |/      |")
            print("       |      (_)")
            print(r"       |      \| ")
            print("       |       |")
            print("       |")
            print("       |")
            print("       |")
            print(" ______|_____")
        elif guess_num == 4:
            print("\nIncorrect guesses left: 4\n")
            print("         -------")
            print("       |/      |")
            print("       |      (_)")
            print(r"       |      \|/ ")
            print("       |       |")
            print("       |")
            print("       |")
            print("       |")
            print(" ______|_____")
        elif guess_num == 3:
            print("\nIncorrect guesses left: 3\n")
            print("        -------")
            print("      |/      |")
            print("      |      (_)")
            print(r"      |      \|/ ")
            print("      |       |")
            print("      |      / ")
            print("      |")
            print("      |")
            print("______|_____")

        elif guess_num == 2:
            print("\nIncorrect guesses left: 2\n")
            print("         -------")
            print("       |/      |")
            print("       |      (_)")
            print(r"       |      \|/ ")
            print("       |       |")
            print(r"       |      / \ ")
            print("       |")
            print("       |")
            print(" ______|_____")
        elif guess_num == 1:
            print("\nIncorrect guesses left: 1\n")
            print("         -------")
            print("       |/      |")
            print("       |      (_)")
            print(r"       |      \|/ ")
            print("       |       |")
            print(r"       |     _/ \ ")
            print("       |")
            print("       |")
            print(" ______|_____")
        elif guess_num == 0:
            print("\nOut of guesses\n")
            print("        -------  ")
            print("       |/      |  ")
            print("       |      (_) ")
            print(r"       |      \|/ ")
            print("       |       |  ")
            print(r"       |     _/ \_")
            print("       |")
            print("       |")
            print(" ______|_____")
            print()
            print("Sorry, you didn't win this time. The word was %s" % word)
            
